#!/bin/sh

echo ==== Install Docker-CE ====
sudo apt-get update
sudo apt-get install \
    apt-transport-https \
    ca-certificates \
    curl \
    software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"
sudo apt-get update
sudo apt-get install -y docker-ce

echo ==== Install Docker-Compose ====
sudo apt-get install -y docker-compose

echo ==== Setting Dockers ====
path=$(cd `dirname $0`;pwd)
cd $path
./check

echo ==== Compose Dockers ====
cd ../FishBase-Dockers/
docker-compose down
docker-compose build --force-rm --no-cache

